name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    # Remove snap Firefox if present (fixes binary issues in Ubuntu latest)
    - name: Remove snap Firefox
      run: sudo snap remove firefox || true

    # Install Firefox ESR (classic binary, compatible with Selenium)
    - name: Install Firefox ESR
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox-esr

    # Install geckodriver (latest release)
    - name: Install geckodriver
      run: |
        GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep 'tag_name' | cut -d\" -f4)
        wget "https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz"
        tar -xzf "geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz"
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    # Run tests
    - run: npm test